# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SachKoVersion1' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SachKoVersion1

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-spinkit', :path => '../node_modules/react-native-spinkit'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  target 'SachKoVersion1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SachKoVersion1-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SachKoVersion1-tvOS

  target 'SachKoVersion1-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
